/*
 * common.h
 *
 *  Created on: 2015Äê10ÔÂ16ÈÕ
 *      Author: Jhon_Qiki
 */

#ifndef SRC_COMMON_H_
#define SRC_COMMON_H_

#define MAX_SIZE 64
#define MAX_MODE_SIZE 8
#define MAX_PATH_SIZE 0xFF

#ifdef __cplusplus
extern "C" {
#endif

/* function status */
typedef enum FUNC_RESULT{
	FUNC_RESULT_NONE = 2,
	FUNC_RESULT_SUCCESS=0,
	FUNC_RESULT_FAILED=1,
	FUNC_RESULT_NULLPOINTER=3,
	FUNC_RESULT_INVALID_PARAMETER=4,
	FUNC_RESULT_SYSCALL_FAILED=5,

	FUNC_RESULT_FILE_OPEN_FAILED = 0x12,
	FUNC_RESULT_FILE_WRITE_FAILED = 0x22,

	FUNC_RESULT_MEMORY_ALLOCATE_FAILED = 0x32,

	FUNC_RESULT_DEV_SPEED_CHANGE_NOT_SUPPORT = 0x42,

	FUNC_RESULT_SPI_LSB_NOT_SUPPORT = 0x52,

	FUNC_RESUTL_I2C_EXCCEED_BLOCK_SIZE = 0x62,
}FUNC_RESULT;


#ifdef __cplusplus
}
#endif

#endif /* SRC_COMMON_H_ */
