/*
 * type_def.h
 * 
 * Created on 11/13/2015
 * 			  Jhon Qiki
 */
#ifndef _H_TYPE_DEF_H_
#define _H_TYPE_DEF_H_

/* function status */
typedef enum FUNC_RESULT{
	FUNC_RESULT_NONE = 2,
	FUNC_RESULT_SUCCESS=0,
	FUNC_RESULT_FAILED=1,
	FUNC_RESULT_NULLPOINTER=3,
	FUNC_RESULT_INVALID_PARAMETER=4,
	FUNC_RESULT_SYSCALL_FAILED=5,

	FUNC_RESULT_FILE_OPEN_FAILED = 0x12,
	FUNC_RESULT_FILE_WRITE_FAILED = 0x22,

	FUNC_RESULT_MEMORY_ALLOCATE_FAILED = 0x32,

	FUNC_RESULT_DEV_SPEED_CHANGE_NOT_SUPPORT = 0x42,

	FUNC_RESULT_SPI_LSB_NOT_SUPPORT = 0x52,

	FUNC_RESUTL_I2C_EXCCEED_BLOCK_SIZE = 0x62,
}FUNC_RESULT;

#endif
